// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPyvoeUsnaVGWxLiZXZUedk4RYTdhbDk8',
    appId: '1:933398544218:web:0d1184c156c235478d7d63',
    messagingSenderId: '933398544218',
    projectId: 'mobile-app-2854c',
    authDomain: 'mobile-app-2854c.firebaseapp.com',
    storageBucket: 'mobile-app-2854c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLX23YvumJq4LIdxzHTs-XvreTXQTAQQ',
    appId: '1:933398544218:android:36335922b214b5088d7d63',
    messagingSenderId: '933398544218',
    projectId: 'mobile-app-2854c',
    storageBucket: 'mobile-app-2854c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtVnI2elqpdXkIKhVL7oFYOMNMZsB-yKI',
    appId: '1:933398544218:ios:764b7fad723a69d18d7d63',
    messagingSenderId: '933398544218',
    projectId: 'mobile-app-2854c',
    storageBucket: 'mobile-app-2854c.appspot.com',
    iosBundleId: 'com.example.barberappointmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtVnI2elqpdXkIKhVL7oFYOMNMZsB-yKI',
    appId: '1:933398544218:ios:ee214ef2654657098d7d63',
    messagingSenderId: '933398544218',
    projectId: 'mobile-app-2854c',
    storageBucket: 'mobile-app-2854c.appspot.com',
    iosBundleId: 'com.example.barberappointmentapp.RunnerTests',
  );
}
